# Generated by Django 6.0.6 on 2026-07-05 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_book_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-created_at']},
        ),
    ]
